services:
    web_sad:
        image: wordpress:6
        volumes:
            - ./target:/var/www/html
        environment:
            - WORDPRESS_DB_USER=manager
            - WORDPRESS_DB_PASSWORD=secret
            - WORDPRESS_DB_HOST=prueba
            - WORDPRESS_DB_NAME=wordpress
        ports:
            - 8090:80

volumes:
    data:
